---
- name: Uninstall RKE2
  hosts: rke2_servers:rke2_agents
  any_errors_fatal: true
  become: true
  tasks:
    - name: Run rke2-uninstall.sh script
      shell: /usr/local/bin/rke2-uninstall.sh
      args:
        chdir: /usr/local/bin/
      ignore_errors: yes
